name: test
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PERL_USE_UNSAFE_INC: 0
      AUTHOR_TESTING: 1
      AUTOMATED_TESTING: 1
      RELEASE_TESTING: 1
    strategy:
      matrix:
        perl:
          [
            "5.36",
            "5.34",
            "5.32",
            "5.30",
            "5.28",
            "5.26",
            "5.24",
            "5.22",
            "5.20",
            "5.18",
            "5.16",
          ]
    name: Perl ${{ matrix.perl }}
    steps:
      - uses: actions/checkout@v3
      - name: perl -V
        run: perl -V
      - name: install dependencies
        uses: perl-actions/install-with-cpm@stable
        with:
          cpanfile: cpanfile
          args: "--no-test --with-configure --with-develop --with-suggests"
      - name: Build.PL
        run: perl Build.PL
      - run: ./Build
      - run: ./Build test

